import {
    AsyncRequest,
    ComponentClass,
    ComponentFunction,
    Events,
    Form,
    Fragment,
    Key,
    Lifecycle,
    PropsClass,
    PropsFunction,
    ReactMemo,
    Refs,
    Routing,
    StateClass,
    StateFunction,
    UseContext,
    UseEffect,
    UseMemo,
    VirtualDom,
} from '../pages/index';

export const routes = [
    { path: 'VirtualDom', element: VirtualDom },
    { path: 'ComponentClass', element: ComponentClass },
    { path: 'ComponentFunction', element: ComponentFunction },
    { path: 'PropsClass', element: PropsClass },
    { path: 'PropsFunction', element: PropsFunction },
    { path: 'StateClass', element: StateClass },
    { path: 'StateFunction', element: StateFunction },
    { path: 'Lifecycle', element: Lifecycle },
    { path: 'Events', element: Events },
    { path: 'Key', element: Key },
    { path: 'Refs', element: Refs },
    { path: 'Fragment', element: Fragment },
    { path: 'ReactMemo', element: ReactMemo },
    { path: 'UseMemo', element: UseMemo },
    { path: 'UseEffect', element: UseEffect },
    { path: 'UseContext', element: UseContext },
    { path: 'Form', element: Form },
    { path: 'Routing', element: Routing },
    { path: 'AsyncRequest', element: AsyncRequest },
];
