import {
  VirtualDom,
  ComponentClass,
  ComponentFunction,
  Events,
  Fragment,
  Home,
  Key,
  Lifecycle,
  NotFound404,
  PropsClass,
  PropsFunction,
  ReactMemo,
  Refs,
  StateClass,
  StateFunction,
  UseEffect,
  UseMemo,
  UseCallback,
  UseRef,
  Context,
  Form,
  AsyncRequest,
  Routing,
} from '../pages/index';

import {
  VIRTUAL__DOM,
  COMPONENT_CLASS,
  COMPONENT_FUNCTION,
  EVENTS,
  FRAGMENT,
  KEY,
  LIFECYCLE,
  PROPS_CLASS,
  PROPS_FUNCTION,
  REACT__MEMO,
  REFS,
  USE_REF,
  STATE_CLASS,
  STATE_FUNCTION,
  CONTEXT,
  USE__EFFECT,
  USE__MEMO,
  USE__CALLBACK,
  FORM,
  ASYNC__REQUEST,
  ROUTING,
} from '../utils/constants/path.constants';

export const routes = [
  { path: '/', element: Home, index: true },
  { path: VIRTUAL__DOM, element: VirtualDom },
  { path: COMPONENT_CLASS, element: ComponentClass },
  { path: COMPONENT_FUNCTION, element: ComponentFunction },
  { path: PROPS_CLASS, element: PropsClass },
  { path: PROPS_FUNCTION, element: PropsFunction },
  { path: STATE_CLASS, element: StateClass },
  { path: STATE_FUNCTION, element: StateFunction },
  { path: LIFECYCLE, element: Lifecycle },
  { path: EVENTS, element: Events },
  { path: KEY, element: Key },
  { path: REFS, element: Refs },
  { path: USE_REF, element: UseRef },
  { path: FRAGMENT, element: Fragment },
  { path: REACT__MEMO, element: ReactMemo },
  { path: USE__MEMO, element: UseMemo },
  { path: USE__CALLBACK, element: UseCallback },
  { path: USE__EFFECT, element: UseEffect },
  { path: CONTEXT, element: Context },
  { path: FORM, element: Form },
  { path: ASYNC__REQUEST, element: AsyncRequest },
  { path: ROUTING, element: Routing },
  { path: '*', element: NotFound404 },
];
